// <auto-generated />
using BakeryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryShop.Data.Migrations
{
    [DbContext(typeof(BakeryShopContext))]
    [Migration("20221208140054_ProductPrice")]
    partial class ProductPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BakeryShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageName = "Bread.jpeg",
                            ProductDescription = "Normal Bread",
                            ProductName = "Bread",
                            ProductPrice = 5m
                        },
                        new
                        {
                            ProductId = 2,
                            ImageName = "BrownBread.jpeg",
                            ProductDescription = "Brown Fresh Bread",
                            ProductName = "Brown Bread",
                            ProductPrice = 10m
                        },
                        new
                        {
                            ProductId = 3,
                            ImageName = "Corwasant.jpeg",
                            ProductDescription = "Fresh Corwasant",
                            ProductName = "Corwasant",
                            ProductPrice = 7.5m
                        },
                        new
                        {
                            ProductId = 4,
                            ImageName = "CupCakes.jpeg",
                            ProductDescription = "Fresh CupCakes",
                            ProductName = "CupCakes",
                            ProductPrice = 15m
                        },
                        new
                        {
                            ProductId = 5,
                            ImageName = "DarkTost.jpeg",
                            ProductDescription = "Fresh DarkTost",
                            ProductName = "DarkTost",
                            ProductPrice = 7.5m
                        },
                        new
                        {
                            ProductId = 6,
                            ImageName = "FrenchBread.jpeg",
                            ProductDescription = "Fresh FrenchBread",
                            ProductName = "FrenchBread",
                            ProductPrice = 35m
                        },
                        new
                        {
                            ProductId = 7,
                            ImageName = "ItalianBread.jpeg",
                            ProductDescription = "Fresh ItalianBread",
                            ProductName = "ItalianBread",
                            ProductPrice = 45m
                        },
                        new
                        {
                            ProductId = 8,
                            ImageName = "Sandwiches.jpeg",
                            ProductDescription = "Fresh Sweet Sandwiches",
                            ProductName = "Sandwiches",
                            ProductPrice = 10m
                        },
                        new
                        {
                            ProductId = 9,
                            ImageName = "WhiteTost.jpeg",
                            ProductDescription = "Fresh WhiteTost",
                            ProductName = "WhiteTost",
                            ProductPrice = 7.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
